# Generated by Django 5.0.1 on 2024-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currency', models.PositiveIntegerField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15)),
                ('change', models.DecimalField(decimal_places=3, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
